apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-webserver
  template:
    metadata:
      labels:
        app: my-webserver
    spec:
      containers:
      - name: webserver
        image: nginx:latest
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-webserver
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default_test.txt: |
    <html>
      <body>
        <h1>Welcome to my webserver!</h1>
      </body>
    </html>

---

apiVersion: v1
kind: Service
metadata:
  name: my-nodeport
spec:
  selector:
    app: my-webserver
  ports:
  - name: http
    port: 30080
    targetPort: 80
  type: NodePort
