apiVersion: fleet.cattle.io/v1alpha1
kind: Fleet

metadata:
  name: my-fleet
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  strategy:
    type: Recreate
  updateStrategy:
    type: RollingUpdate
  maxSurgePercent: 25
  podManagementPolicy: AlwaysReady
  selfHealing: true

template:
  spec:
    containers:
    - name: webserver
      image: nginx:latest
      command: ["nginx", "-g", "daemon off;"]
      ports:
      - containerPort: 80

deployment:
  spec:
    selector:
      matchLabels:
        app: my-app
    replicas: 3
    template:
      spec:
        containers:
        - name: webserver
          image: nginx:latest
          command: ["nginx", "-g", "daemon off;"]
          ports:
          - containerPort: 80

service:
  selector:
    app: my-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

nodeport:
  selector:
    app: my-app
  ports:
  - name: http
    port: 30080
    targetPort: 80
  type: NodePort
